* niĝ₂-nam nu-kal - index note
niĝ₂-nam nu-kal - nothing is of value 240222a
This is common to all versions, in most versions this are the opening lines.
niĝ₂-nam nu-kal - death is the share of men 240226a
niĝ₂-nam nu-kal - life spend in joy 240227b
niĝ₂-nam nu-kal - plan failed, goods burnt, money lost, house destroyed 240226b
niĝ₂-nam nu-kal - tallest one won't reach heavens- 240227a
This has parrales in proverb collections, in Sumerian Bilgamesh and Huwawa, and in Ballade of Early Rulers.
In "Religious Redaction in Qohelet in Light of Mesopotamian Vanity Literature", Nili Samet argues that some versions of niĝ₂-nam were readcted to be more religious and to soften the vanity theme.
E.g. adding at the end of the composition:
"For him who gives [food] to the gods, for him who gives good stuff to the gods, (life is found).”
or in the middle:
"Whatever a man possesses is bestowed to him by his personal god as a gift.
If his god had looked favorably upon him, his ears are opened,
His protective deities and his personal god will be present in his body,
His smoke offering will not cease . . ."
