* Nothing is of value Version A
:PROPERTIES:
  :ANKI_DECK: sumerian_philosophy
  :ANKI_NOTE_TYPE: Cloze
  :END:
** text
240211a
#+begin_quote
1.
niĝ₂-nam nu-kal zi ku₇-ku₇-dam
niĝ₂-nam NEG.kal zi ku₇-ku₇.?
anything not.to-be-valuable life/breath to-be-sweet.? 
Everything is worthless, but life is sweet.

2.
me-na-am₃ niĝ₂-tuku lu₂ la-ba-an-tuku lu₂ niĝ₂-tuku ba-an-tuku
me-na.? niĝ₂-tuku lu₂ la.?.tuku lu₂ niĝ₂-tuku ?.tuku
when.? rich person NEG.?.to-have person rich ?.to-have
When a man does not have wealth, (that) man has wealth.

5.
sukud-du an-na-še₃ nu-um-da-la₂
sukud.? an.?.šu ?.la₂
to-be-high sky/haven.?.hand ?.to-hang
The tallest one cannot reach the sky.

6.


(l) Nothing is of value, but life itself should be sweet-tasting.
(2) Whenever a man does not own some piece of property, that man owns some property.
(5) (Even) the tallest one cannot reach to the sky;
(6) (Even) the broadest one cannot go down to the Netherworld.
(?) (Even) the strongest one cannot [stretch himseln on Earth.
(8) The good life, let it be defiled in joy!
(9) Let the "race" be spent injoy!
(10) A man's good house is the house in which he has to live!
#+end_quote
** other
Bendt Alster "Wisdom of Ancient Sumer" p.270
